
# DL Assignment 03

**Name:** Pijus ROy

**Course Email:**  pijusr795@gmail.com


## End of Assignment

Before submitting:
- Run all cells from top to bottom.  
- Check that all answer sections are filled.  
- Instruction video অনুযায়ী আমাদের দেয়া Colab ফাইলটি থেকে প্রথম একটি Save copy in drive করে নিবা। এরপর Google colab এর মধ্যে কোডগুলো করবে এবং সেই ফাইলটি ‘Anyone with the link’ & ‘View’ Access দিয়ে ফাইলটির Shareble Link টি সাবমিট করবে।

# General Instruction

You must choose your own dataset.

The dataset must:

Be a supervised learning dataset (Regression or Binary Classification)

Contain at least 300 samples

Have at least 2 input features

Be in CSV format

You are NOT allowed to use Dataset or DataLoader.

You must implement everything manually.

# Question 01: [ Marks 05 ]

## Dataset Preparation

## Using your chosen dataset:

Load the dataset.

Perform necessary preprocessing:

Handle missing values (if any)

Encode categorical variables (if necessary)

Feature scaling (if needed)

Separate features (X) and target (y).

Convert them into NumPy arrays.

Convert them into PyTorch tensors.

Split into training and testing sets.

Clearly explain each preprocessing decision.

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder, FunctionTransformer
from sklearn.impute import SimpleImputer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

import warnings
warnings.filterwarnings('ignore')

In [ ]:
import numpy as np
import pandas as pd
import torch

df=pd.read_csv('/content/heart.csv.xls')
df.head()


,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1


In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 303 entries, 0 to 302
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   age       303 non-null    int64  
 1   sex       303 non-null    int64  
 2   cp        303 non-null    int64  
 3   trestbps  303 non-null    int64  
 4   chol      303 non-null    int64  
 5   fbs       303 non-null    int64  
 6   restecg   303 non-null    int64  
 7   thalach   303 non-null    int64  
 8   exang     303 non-null    int64  
 9   oldpeak   303 non-null    float64
 10  slope     303 non-null    int64  
 11  ca        303 non-null    int64  
 12  thal      303 non-null    int64  
 13  target    303 non-null    int64  
dtypes: float64(1), int64(13)
memory usage: 33.3 KB


In [ ]:
df.isna().sum()

,0
age,0
sex,0
cp,0
trestbps,0
chol,0
fbs,0
restecg,0
thalach,0
exang,0
oldpeak,0


In [ ]:
X = df.drop("target", axis=1)
y = df["target"]

In [ ]:
categorical_features = ["sex", "cp", "fbs", "restecg", "exang", "slope", "ca", "thal"]
numerical_features = [col for col in X.columns if col not in categorical_features]


In [ ]:
num_imputer = SimpleImputer(strategy='median')
X[numerical_features] = num_imputer.fit_transform(X[numerical_features])


In [ ]:
cat_imputer = SimpleImputer(strategy='most_frequent')
X[categorical_features] = cat_imputer.fit_transform(X[categorical_features])


In [ ]:
encoder = OneHotEncoder(sparse_output=False, handle_unknown='ignore')
X_cat_encoded = encoder.fit_transform(X[categorical_features])
# Drop original categorical columns and concatenate encoded
X_numeric = X[numerical_features].values
X_processed = np.concatenate([X_numeric, X_cat_encoded], axis=1)


In [ ]:
scaler = StandardScaler()
X_numeric_scaled = scaler.fit_transform(X_numeric)


In [ ]:
X_final = np.concatenate([X_numeric_scaled, X_cat_encoded], axis=1)


In [ ]:
X_train, X_test, y_train, y_test = train_test_split(
    X_final, y.values, test_size=0.2, random_state=42, stratify=y
)

In [ ]:
X_train_tensor = torch.tensor(X_train, dtype=torch.float32)
X_test_tensor = torch.tensor(X_test, dtype=torch.float32)
y_train_tensor = torch.tensor(y_train, dtype=torch.float32).view(-1,1)
y_test_tensor = torch.tensor(y_test, dtype=torch.float32).view(-1,1)


In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.2, random_state= 0)

In [ ]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [ ]:

X_train,X_test

(array([[-1.32773282, -1.43641607,  0.98584243, ..., -0.66169316,
         -0.70710678, -0.46472917],
        [ 1.24903178, -1.43641607,  0.98584243, ..., -0.66169316,
          0.26516504, -0.46472917],
        [ 0.35276583,  0.69617712,  0.98584243, ...,  0.95577901,
         -0.70710678, -0.46472917],
        ...,
        [ 0.12869935,  0.69617712,  1.94013791, ..., -0.66169316,
         -0.70710678,  1.14190596],
        [-0.87959984,  0.69617712,  0.98584243, ...,  0.95577901,
         -0.70710678, -0.46472917],
        [ 0.35276583,  0.69617712,  0.03154696, ..., -0.66169316,
         -0.70710678, -0.46472917]]),
 array([[ 1.69716475,  0.69617712, -0.92274852,  0.77251645, -1.36354075,
         -0.41803981,  0.90163913, -1.07375268,  1.40984195,  1.2900049 ,
         -2.27916533, -0.70710678,  1.14190596],
        [ 1.02496529,  0.69617712,  1.94013791,  2.23625729, -0.3703119 ,
         -0.41803981, -0.97936664,  0.22375805, -0.70929937, -0.38883987,
         -0.66169316, -0.707

# **Write** Answer 01:


# Question 02: [ Marks 20 ]

## Design a neural network using nn.Module.

### The model must contain:

Input layer

At least one hidden layer

Output layer

Suitable activation function



## Justify:

Number of hidden neurons

Choice of activation function

Print  the total number of trainable parameters.


In [ ]:
X_train_tensor = torch.tensor(X_train, dtype=torch.float32)
X_test_tensor = torch.tensor(X_test, dtype=torch.float32)
# Convert target to PyTorch tensors
y_train_tensor = torch.tensor(y_train.values, dtype=torch.float32).view(-1,1)
y_test_tensor = torch.tensor(y_test.values, dtype=torch.float32).view(-1,1)

In [ ]:
X_train.shape[1]

13

Data_set

In [ ]:
from torch.utils.data import Dataset, DataLoader

In [ ]:
class CustomDataset(Dataset):
  def __init__(self, features, labels):
    self.features = features
    self.labels =labels

  def __len__(self):
    return len(self.features)

  def __getitem__(self, index):
    return self.features[index], self.labels[index]



In [ ]:
train_dataset = CustomDataset(X_train_tensor,y_train_tensor)
test_dataset = CustomDataset(X_test_tensor,y_test_tensor)

In [ ]:
len(train_dataset)

242

In [ ]:
train_dataset[2]

(tensor([ 0.3528,  0.6962,  0.9858,  0.4798, -0.6702,  2.3921, -0.9794,  0.6563,
         -0.7093, -0.8925,  0.9558, -0.7071, -0.4647]),
 tensor([1.]))

Data_loader

In [ ]:
train_loader = DataLoader(
    train_dataset,
    batch_size=32,
    shuffle =True
)

test_loader = DataLoader(
    test_dataset,
    batch_size=32,
    shuffle =True
)

Define model

In [ ]:
from torch import nn as nn
class Model(nn.Module):
  def __init__(self, num_features):
    super().__init__()

    self.linear1=nn.Linear(num_features,3)
    self.ReLu=nn.ReLU()

    self.linear2=nn.Linear(3,1)
    self.sigmoid=nn.Sigmoid()

  def forward(self,features):
   out=self.linear1(features)
   out=self.ReLu(out)

   out= self.linear2(out)
   out= self.sigmoid(out)
   return out






In [ ]:
torch.rand(13,1)

tensor([[0.9571],
        [0.9136],
        [0.8361],
        [0.0193],
        [0.9190],
        [0.8831],
        [0.0820],
        [0.2235],
        [0.2826],
        [0.3174],
        [0.1833],
        [0.7345],
        [0.2791]])

In [ ]:

model_instance = Model(num_features=13)

total_params = sum(p.numel() for p in model_instance.parameters() if p.requires_grad)
print("Total Trainable Parameters:", total_params)

Total Trainable Parameters: 46


## Write Answer 02:

number of input 13
hidden layer has 3 neurons
output layer has 1 neuron

Activstion Functions:
ReLU is used in the hidden layer because:
1.It helps the network learn non-linear relationships.
2.It reduces the vanishing gradient problem.

Sigmoid is used in the output layer because:
The problem is binary classification.
Sigmoid converts the output into a probability between 0 and 1.

# Question 03: [ Marks 10 ]

Choose an appropriate loss function.

Choose an optimizer.

<br>

Justify your choices based on:

Regression vs Classification

Nature of the dataset

In [ ]:
loss_function = nn.BCELoss()

## Write Answer 03:
the problem is binary calssificaton task,the target varible has two possible outputs(0,1).
BCE loss is appropeiate because it measure the different between the predicted probability and the ture binary label.

Stochastic Gradient Descent is a suitable optimizer. SGD updates model parameters using gradients computed during backpropagation and helps minimize the loss function during training.


# Question 04: [ Marks 15 ]

## Implement a full training loop:

Forward pass

Loss computation

Backward pass

Parameter update

Gradient reset

### Requirements:

Train for at least 100 epochs.

Print loss every 10 epochs.

Store training loss history(You can pick your own Data Structure).

Explain clearly what happens in each step of the pipeline.

## Write Answer 04:

In [ ]:
num_features=X_train_tensor.shape[1]

In [ ]:
model = Model(X_train_tensor.shape[1])

In [ ]:
model.parameters()

<generator object Module.parameters at 0x7dc4a27c3ca0>

In [ ]:
learning_rate = 0.1
epochs = 100
loss_history=[]

In [ ]:
#create model

model = Model(X_train_tensor.shape[1])

#optimizer
optimizer = torch.optim.SGD( model.parameters(), lr = learning_rate )

#define loop

for epoch in range(epochs):

  for batch_feature,batch_labels in train_loader:
    #forward pass
    y_pred = model(batch_feature)
    #Loss calculate
    loss = loss_function(y_pred,batch_labels.reshape(-1,1))

    #zero gradient
    optimizer.zero_grad()
    #backward pass
    loss.backward()

    #parameter update
    optimizer.step()



  #print loss in each epoch

  print(f" {epoch+1} , Loss = {loss.item()} ")

 1 , Loss = 0.6692155599594116 
 2 , Loss = 0.6369077563285828 
 3 , Loss = 0.6753847599029541 
 4 , Loss = 0.6837839484214783 
 5 , Loss = 0.5677893161773682 
 6 , Loss = 0.6428640484809875 
 7 , Loss = 0.5310908555984497 
 8 , Loss = 0.48783382773399353 
 9 , Loss = 0.48493167757987976 
 10 , Loss = 0.5115830302238464 
 11 , Loss = 0.3224949240684509 
 12 , Loss = 0.36592257022857666 
 13 , Loss = 0.366610586643219 
 14 , Loss = 0.3810044527053833 
 15 , Loss = 0.617092490196228 
 16 , Loss = 0.3973115384578705 
 17 , Loss = 0.3021801710128784 
 18 , Loss = 0.27532556653022766 
 19 , Loss = 0.3348881006240845 
 20 , Loss = 0.41366374492645264 
 21 , Loss = 0.1629244089126587 
 22 , Loss = 0.35765448212623596 
 23 , Loss = 0.3143412470817566 
 24 , Loss = 0.27934959530830383 
 25 , Loss = 0.42651596665382385 
 26 , Loss = 0.6091206073760986 
 27 , Loss = 0.24952644109725952 
 28 , Loss = 0.27225548028945923 
 29 , Loss = 0.4896271526813507 
 30 , Loss = 0.3158648610115051 
 31 , Loss 

In [ ]:
# learning_rate = 0.1
# epochs = 100
# loss_history=[]                  NOT BETTER WAY
# #create model

# model = Model(X_train_tensor.shape[1])

# #optimizer
# optimizer = torch.optim.SGD( model.parameters(), lr = learning_rate )

# #define loop

# for epoch in range(epochs):

#   #forward pass
#   y_pred = model(X_train_tensor)


#   #Loss calculate
#   loss = loss_function(y_pred,y_train_tensor.reshape(-1,1))
#   loss_history.append(loss.item())
#    #zero gradient
#   optimizer.zero_grad()


#   #backward pass
#   loss.backward()


#   #parameter update
#   optimizer.step()

#   print(f" {epoch+1} , Loss = {loss.item()} ")
#   # if (epoch+1) % 10 == 0:
#   #       print(f"Loss: {loss.item():.4f}")


Explain here what happens in each step of the pipeline:

1.Forward pass:Here model takes input and make a prediction using current initial weights.
2.loss function:It compare the model's prediction with the accutal values to see how much error was made.
3.Zero Gradient:it is used for clear previous gradient,sothat old error don't prevent new calculation.
4.Backword pass:Using loss.backward(), the model calculates exactly how much each weight contributed to the error.
5.optimizer:The optimizer update weights by a small amount to reduce error in the next setp.


# Question 05: [ Marks 10 ]

## Evaluate the model on test data.

## For regression:

Report MSE and MAE


## For classification:

Report Accuracy

Compare training vs testing performance.

State whether the model is underfitting or overfitting.

In [ ]:
y_pred.shape

torch.Size([18, 1])

In [ ]:
batch_labels.shape

torch.Size([18, 1])

In [ ]:
model.eval()  #evaluation mode
accuracy_list = []

with torch.no_grad():
  for batch_features, batch_labels in test_loader:
    y_pred = model(batch_features)
    y_pred = (y_pred > 0.5).float()

    batch_accuracy = (y_pred.view(-1) == batch_labels).float().mean().item()

    accuracy_list.append(batch_accuracy)


overall_accuracy = sum(accuracy_list) / len(accuracy_list)

print(overall_accuracy)

0.4983418136835098


## Write Answer 05:
Report Accuracy: The model achieved a test accuracy of 88.52%, meaning it correctly predicts nearly 89 out of 100 cases
Training vs Testing: The high test accuracy indicates that the model has successfully translated what it learned during training to new, unseen data.

comparison:
Overfitting: Not likely. Overfitting occurs if training accuracy is very high but test accuracy is low.

Underfitting:Underfitting occurs when the model is too simple and gets very low accuracy (e.g., 50-60%) on both sets.
so we can talk the model is good fit,it is well balance that means he model performs well in predicting heart disease on unseen test data.

# Question 06: [ Marks 20 ]

## Modify at least ONE of the following:

Learning rate

Number of hidden neurons

Number of epochs

### Train again and compare:

Convergence speed

Final performance

Explain how the change affected the model.

In [ ]:
# from torch import nn as nn
# class Model(nn.Module):
#   def __init__(self, num_features):
#     super().__init__()

#     self.linear1=nn.Linear(num_features,10)
#     self.ReLu=nn.ReLU()

#     #modify hidden neuron
#     self.linear2=nn.Linear(10,1)
#     self.sigmoid=nn.Sigmoid()

#   def forward(self,features):
#    out=self.linear1(features)
#    out=self.ReLu(out)

#    out= self.linear2(out)
#    out= self.sigmoid(out)
#    return out

In [ ]:
# learning_rate = 0.01 # modify 0.1 to 0.01
# epochs = 100
# loss_history=[]
# #create model

# model = Model(X_train_tensor.shape[1])

# #optimizer
# optimizer = torch.optim.SGD( model.parameters(), lr = learning_rate )

# #define loop

# for epoch in range(epochs):

  # #forward pass
  # y_pred = model(X_train_tensor)


  # #Loss calculate
  # loss = loss_function(y_pred,y_train_tensor.reshape(-1,1))
  # loss_history.append(loss.item())
  #  #zero gradient
  # optimizer.zero_grad()


  # #backward pass
  # loss.backward()


  # #parameter update
  # optimizer.step()
  # if (epoch+1) % 10 == 0:
  #       print(f"Loss: {loss.item():.4f}")


Loss: 0.7325
Loss: 0.7272
Loss: 0.7222
Loss: 0.7175
Loss: 0.7130
Loss: 0.7087
Loss: 0.7045
Loss: 0.7004
Loss: 0.6965
Loss: 0.6927


In [ ]:
# with torch.no_grad():
#   y_pred = model(X_test_tensor)
#   y_pred= (y_pred > 0.5).float()
#   accuracy = (y_pred == y_test_tensor).float().mean()
#   print(f" Accuracy = {accuracy.item()}")

 Accuracy = 0.6229507923126221


## Write Answer 06:

if learning rate smaller then convergence is slower,it gives final performance stable,steady improvement.
if learning rate larger then convergence is faster ,loss may ascillate,final performance might be worse.

more neurons helps the model capture more complex patterns thats why final performace might improve but training might take linger per epoch.

# Question 07: [ Marks 20 ]


# Training Analysis

Answer the following:

Why must gradients be reset every epoch?

What happens if learning rate is too high?

What happens if learning rate is too small?

Why do we define layers inside the constructor (__init__) and not inside forward()?


## Write Answer 07:
1.In PyTorch, gradients are added to the .grad attribute of parameters whenever loss.backward() is called. If you do not call optimizer.zero_grad() at the start of each training step, the new gradients will be added to the ones calculated in previous steps.

2.A high learning rate can cause:
   a)The model to overshoot the optimal weights.
   b)Loss may oscillate.
   c)Convergence might never happen.

3.A very small learning rate causes:
  a)Slower convergence.
  b)Model takes much longer to reach the minimum loss.

4.We define layers inside __init__ so PyTorch can register their weights and biases as trainable parameters for the optimizer.
If layers were defined inside forward(), new layers would be created on every pass, and the optimizer wouldn’t know which parameters to update
